version: '3'

networks:
  network:
    driver: bridge

services:
  api:
    container_name: exampleRMQ
    environment:
      - NODE_ENV=${NODE_ENV}
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: [ "yarn", "start:local" ]
    env_file:
      - .env.local
    ports:
      - ${PORT}:${PORT}
#    depends_on:
#      - postgres
    networks:
      - network
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - network
    depends_on:
      - cache
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data

volumes:
  cache:
    driver: local

