version: '3'

services:
  ms:
    container_name: exampleRMQ
    environment:
      - NODE_ENV=${NODE_ENV}
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: [ "yarn", "start:local" ]
    env_file:
      - .env.local
    ports:
      - ${PORT}:${PORT}
